version: "3"
services:
  datascience-notebook:
    container_name: getting-started-datascience-notebook
    image: jupyter/datascience-notebook
    volumes:
      - ./:/home/jovyan/work
    ports:
      - 8888:8888
